In [12]:
iterable = (a*a for a in range(8))
print(iterable)

<generator object <genexpr> at 0x0000022BAE260E10>


In [2]:
arr=np.arange(0,24)

In [3]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
print(arr.reshape(4,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


[[0.53921686 0.19719273 0.4193319 ]
 [0.2067307  0.4143255  0.16326872]]
