In [2]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
temp=arr
print(id(arr),id(temp))

2298912105616 2298912105616


In [3]:
temp[0]=1000
print(arr)

[1000    2    3    4    5]


In [9]:
v=arr.view()
print(v)
print(id(arr),id(v))

[1000    2    3    4    5]
2298912105616 2299153650896


In [10]:
arr[0]=1
print(v)

[1 2 3 4 5]


In [11]:
c=arr.copy()
print(id(arr),id(c))
arr[0]=2
print(c)

2298912105616 2298912843184
[1 2 3 4 5]


In [20]:
arr = np.arange(1, 13).reshape(2, 6)
print(arr, '\n')

col = np.arange(5, 11).reshape(1, 6)
print(col,'\n')
arr_col = np.append(arr, col, axis=0)
print(arr_col, '\n')
 
row = np.array([1, 2]).reshape(2, 1)
print(row,'\n')
arr_row = np.append(arr, row, axis=1)
print(arr_row,'\n')

print(np.concatenate((arr,row),axis=1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[ 5  6  7  8  9 10]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

[[1]
 [2]] 

[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]] 

[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [22]:
arr[:,[0,5]]=arr[:,[5,0]]
print(arr)

[[ 6  2  3  4  5  1]
 [12  8  9 10 11  7]]


In [36]:
new_arr=arr[np.newaxis,...,np.newaxis]
print(new_arr,new_arr.shape,sep='\n')
expand=np.expand_dims(arr,axis=1)
print(expand.shape,expand)
re=arr.reshape((2,3,2))
print(re.shape)

temp2=np.expand_dims(arr,axis=(0,3,2))
print(temp2.shape)

[[[[ 6]
   [ 2]
   [ 3]
   [ 4]
   [ 5]
   [ 1]]

  [[12]
   [ 8]
   [ 9]
   [10]
   [11]
   [ 7]]]]
(1, 2, 6, 1)
(2, 1, 6) [[[ 6  2  3  4  5  1]]

 [[12  8  9 10 11  7]]]
(2, 3, 2)
(1, 2, 1, 1, 6)


In [39]:
array_1 = np.array([1, 2,3]) 
array_2 = np.array([5, 6,7]) 

print(np.stack((array_1,array_2),axis=1))

[[1 5]
 [2 6]
 [3 7]]


In [40]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [42]:
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

print(np.vsplit(matrix, 2))


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [11]:
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
print('Original Array :' ,
      arr2D, sep = '\n')
 
uniqueRows = np.unique(arr2D)
     
print('Unique Rows:',
      uniqueRows, sep = '\n')

Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[11 12 13 16]
