In [1]:
import numpy as np

In [2]:
#Creating an array 
arr=np.array([[1,2,3],[4,2,5]])

In [4]:
# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [5]:
# create an array from a regular Python list or tuple 

a=np.array([[1,2,4],[5,8,7]],dtype='float')
b=np.array((1,3,2))
print(a,b)

[[1. 2. 4.]
 [5. 8. 7.]] [1 3 2]


In [10]:
c=np.zeros((3,4))
d=np.ones((2,3))
e=np.full((5,5),1,dtype='complex')
f=np.random.random((3,3))
print(c)
print(d)
print(e)
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[[0.73520331 0.53931272 0.63396063]
 [0.3657986  0.96654372 0.14527276]
 [0.24637014 0.39434585 0.66585155]]


In [14]:
g=np.arange(0,30,3)
print(g)

h=np.linspace(0,5,20)
print(h)

[ 0  3  6  9 12 15 18 21 24 27]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [17]:
i=np.array([[1, 2, 3, 4], [5, 2, 4, 2], [1, 2, 0, 1]])
j=i.reshape(2,2,3)
k=i.flatten()

print(i)
print(j)
print(k)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [26]:
# indexing in numpy 
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 

# Slicing array 
temp = arr[:2, ::2] 

print(temp)

#Integer Array Indexing
temp=arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print(temp)

# boolean array indexing
cond = arr > 0 # cond is a boolean array 
temp = arr[cond]
print(cond)
print(temp)

temp=arr[(0, 1, 2, 3), (3, 2, 1, 0)]
print(temp)


temp=arr.T
print(temp)

[[-1.  0.]
 [ 4.  6.]]
[4. 6. 0. 3.]
[[False  True False  True]
 [ True False  True False]
 [ True False  True  True]
 [ True False  True  True]]
[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]
[4. 6. 0. 3.]
[[-1.   4.   2.6  3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]]


In [28]:
#Operations on arr 
print(arr+2)
print(arr*2)
print(arr**2)

[[ 1.   4.   2.   6. ]
 [ 6.   1.5  8.   2. ]
 [ 4.6  2.   9.  10. ]
 [ 5.  -5.   6.   4. ]]
[[ -2.    4.    0.    8. ]
 [  8.   -1.   12.    0. ]
 [  5.2   0.   14.   16. ]
 [  6.  -14.    8.    4. ]]
[[ 1.    4.    0.   16.  ]
 [16.    0.25 36.    0.  ]
 [ 6.76  0.   49.   64.  ]
 [ 9.   49.   16.    4.  ]]


In [29]:
print(arr.max(),arr.max(axis=1),arr.max(axis=0),arr.sum(),arr.cumsum(axis=1))
#axis =1 represent row wise 
#axis =0 represent column wise
#cumsum means cumulative sum

#Unary Operators

8.0 [4. 6. 8. 4.] [4. 2. 7. 8.] 34.1 [[-1.   1.   1.   5. ]
 [ 4.   3.5  9.5  9.5]
 [ 2.6  2.6  9.6 17.6]
 [ 3.  -4.   0.   2. ]]


In [31]:
#Binary Operators

a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 

print(a+b)
print(a*b) #elementwise multiplication
print(a.dot(b)) #matrix multiplication

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [32]:
#ufuncs

# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print (np.sin(a)) 
  
# exponential values 
a = np.array([0, 1, 2, 3]) 
print ( np.exp(a)) 
  
# square root of array values 
print (np.sqrt(a)) 


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [38]:
#Sorting The np array

a=np.array([[1,4,3],[7,2,9],[3,0,6]])

print(np.sort(a,axis=None))
print(np.sort(a,axis=1))
print(np.sort(a,axis=0,kind='mergesort'))


#set alias names for dtypes

dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]

values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes) 
print(np.sort(arr,order='name'))
print(np.sort(arr,order=['grad_year','cgpa']))

[0 1 2 3 3 4 6 7 9]
[[1 3 4]
 [2 7 9]
 [0 3 6]]
[[1 0 3]
 [3 2 6]
 [7 4 9]]
[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
