In [1]:
import pandas as pd
 
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
 
arr = df.to_numpy()
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [3]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df = pd.DataFrame(dict,index=[1,2,3,4])

print(df)
 

     name  degree  score
1  aparna     MBA     90
2  pankaj     BCA     40
3  sudhir  M.Tech     80
4   Geeku     MBA     98


In [17]:
lst=['My','name','is','Peyush','Jindal','.']
df=pd.DataFrame(lst,index=[1,2,3,4,5,6])
df.columns=['Sent']
print(df)

     Sent
1      My
2    name
3      is
4  Peyush
5  Jindal
6       .


In [26]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        }
  
df = pd.DataFrame(data)
 
print(df[['Name', 'Age']])

     Name  Age
0     Jai   27
1  Princi   24
2  Gaurav   22
3    Anuj   32


In [27]:
address = ['Delhi', 'Bangalore', 'Chennai', 'Patna']

df['Address'] = address

print(df)




     Name  Age    Address
0     Jai   27      Delhi
1  Princi   24  Bangalore
2  Gaurav   22    Chennai
3    Anuj   32      Patna


In [28]:
data = pd.read_csv("nba.csv", index_col ="Name" )
 
data.drop(["Team", "Weight"], axis = 1, inplace = True)
 
print(data)

               Number Position   Age Height            College     Salary
Name                                                                     
Avery Bradley     0.0       PG  25.0    6-2              Texas  7730337.0
Jae Crowder      99.0       SF  25.0    6-6          Marquette  6796117.0
John Holland     30.0       SG  27.0    6-5  Boston University        NaN
R.J. Hunter      28.0       SG  22.0    6-5      Georgia State  1148640.0
Jonas Jerebko     8.0       PF  29.0   6-10                NaN  5000000.0
...               ...      ...   ...    ...                ...        ...
Shelvin Mack      8.0       PG  26.0    6-3             Butler  2433333.0
Raul Neto        25.0       PG  24.0    6-1                NaN   900000.0
Tibor Pleiss     21.0        C  26.0    7-3                NaN  2900000.0
Jeff Withey      24.0        C  26.0    7-0             Kansas   947276.0
NaN               NaN      NaN   NaN    NaN                NaN        NaN

[458 rows x 6 columns]


In [29]:
data = pd.read_csv("nba.csv", index_col ="Name")
 
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
 
 
print(first, "\n\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


In [39]:
data = pd.read_csv("nba.csv", index_col ="Name")

df.head(10)

new_row = pd.DataFrame({'Name':'Geeks', 'Team':'Boston', 'Number':3,
                        'Position':'PG', 'Age':33, 'Height':'6-2',
                        'Weight':189, 'College':'MIT', 'Salary':99999}, index =[0])
                                     
df = pd.concat([new_row, df]).reset_index(drop = True)
df.head(5)

Name    Team  Number Position  Age Height  Weight College   Salary  \
0   Geeks  Boston     3.0       PG   33    6-2   189.0     MIT  99999.0   
1   Geeks  Boston     3.0       PG   33    6-2   189.0     MIT  99999.0   
2   Geeks  Boston     3.0       PG   33    6-2   189.0     MIT  99999.0   
3     Jai     NaN     NaN      NaN   27    NaN     NaN     NaN      NaN   
4  Princi     NaN     NaN      NaN   24    NaN     NaN     NaN      NaN   

     Address  
0        NaN  
1        NaN  
2        NaN  
3      Delhi  
4  Bangalore

In [40]:
data.drop(["Avery Bradley", "John Holland", "R.J. Hunter",
                            "R.J. Hunter"], inplace = True)

In [43]:
print(data.head())

                         Team  Number Position   Age Height  Weight  \
Name                                                                  
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0   
Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
Kelly Olynyk   Boston Celtics    41.0        C  25.0    7-0   238.0   

                 College      Salary  
Name                                  
Jae Crowder    Marquette   6796117.0  
Jonas Jerebko        NaN   5000000.0  
Amir Johnson         NaN  12000000.0  
Jordan Mickey        LSU   1170960.0  
Kelly Olynyk     Gonzaga   2165160.0  


In [47]:
data = pd.read_csv("nba.csv", index_col ="Team")

print(data.loc["Boston Celtics"])

                           Name  Number Position   Age Height  Weight  \
Team                                                                    
Boston Celtics    Avery Bradley     0.0       PG  25.0    6-2   180.0   
Boston Celtics      Jae Crowder    99.0       SF  25.0    6-6   235.0   
Boston Celtics     John Holland    30.0       SG  27.0    6-5   205.0   
Boston Celtics      R.J. Hunter    28.0       SG  22.0    6-5   185.0   
Boston Celtics    Jonas Jerebko     8.0       PF  29.0   6-10   231.0   
Boston Celtics     Amir Johnson    90.0       PF  29.0    6-9   240.0   
Boston Celtics    Jordan Mickey    55.0       PF  21.0    6-8   235.0   
Boston Celtics     Kelly Olynyk    41.0        C  25.0    7-0   238.0   
Boston Celtics     Terry Rozier    12.0       PG  22.0    6-2   190.0   
Boston Celtics     Marcus Smart    36.0       PG  22.0    6-4   220.0   
Boston Celtics  Jared Sullinger     7.0        C  24.0    6-9   260.0   
Boston Celtics    Isaiah Thomas     4.0       PG  2

In [67]:
data = pd.read_csv("nba.csv", index_col =["Name"])
print(data.loc["Avery Bradley":"Isaiah Thomas"])

                           Team  Number Position   Age Height  Weight  \
Name                                                                    
Avery Bradley    Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder      Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland     Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter      Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko    Boston Celtics     8.0       PF  29.0   6-10   231.0   
Amir Johnson     Boston Celtics    90.0       PF  29.0    6-9   240.0   
Jordan Mickey    Boston Celtics    55.0       PF  21.0    6-8   235.0   
Kelly Olynyk     Boston Celtics    41.0        C  25.0    7-0   238.0   
Terry Rozier     Boston Celtics    12.0       PG  22.0    6-2   190.0   
Marcus Smart     Boston Celtics    36.0       PG  22.0    6-4   220.0   
Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0   
Isaiah Thomas    Boston Celtics     4.0       PG  2